# Generated by Django 2.2.7 on 2019-12-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ekgModel',
            fields=[
                ('e_uuid', models.AutoField(primary_key=True, serialize=False)),
                ('e_recordName', models.CharField(max_length=50)),
                ('e_ppDir', models.CharField(max_length=50)),
            ],
        ),
    ]
