# Generated by Django 2.2.7 on 2020-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_name',
            new_name='c_rowEight',
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowEleven',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowFive',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowFour',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowFourteen',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowNine',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowOne',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowSeven',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowSix',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowTen',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowThirteen',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowThree',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowTwelve',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='c_rowTwo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
