# Generated by Django 2.2.7 on 2020-01-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_viewer', '0002_auto_20200104_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowEight',
            new_name='c_colEight',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowEleven',
            new_name='c_colEleven',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowFive',
            new_name='c_colFive',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowFour',
            new_name='c_colFour',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowFourteen',
            new_name='c_colFourteen',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowNine',
            new_name='c_colNine',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowOne',
            new_name='c_colOne',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowSeven',
            new_name='c_colSeven',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowSix',
            new_name='c_colSix',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowTen',
            new_name='c_colTen',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowThirteen',
            new_name='c_colThirteen',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowThree',
            new_name='c_colThree',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowTwelve',
            new_name='c_colTwelve',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='c_rowTwo',
            new_name='c_colTwo',
        ),
    ]
