# Generated by Django 2.2.7 on 2020-01-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_viewer', '0003_auto_20200104_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvFileModel',
            fields=[
                ('f_uuid', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('f_firstRow', models.IntegerField(max_length=20)),
                ('f_lasttRow', models.IntegerField(max_length=20)),
            ],
        ),
    ]
