# Generated by Django 2.2.7 on 2020-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_viewer', '0004_csvfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfilemodel',
            name='c_parameter',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
