# Generated by Django 2.2.7 on 2020-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_viewer', '0005_csvfilemodel_c_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='c_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
