# Generated by Django 2.2.7 on 2020-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_viewer', '0006_csvmodel_c_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='c_parameter',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
