# Generated by Django 2.2.7 on 2020-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dcmModel',
            fields=[
                ('d_uuid', models.AutoField(primary_key=True, serialize=False)),
                ('d_patientuid', models.CharField(max_length=300)),
                ('d_seriesuid', models.CharField(max_length=300)),
                ('d_studyuid', models.CharField(max_length=300)),
                ('d_imageuid', models.CharField(max_length=300)),
                ('d_sopinstanceuid', models.CharField(max_length=300)),
            ],
        ),
    ]
